using Unilyze;

namespace Unilyze.Tests.Discovery;

public sealed class DefaultExcludesTests : IDisposable
{
    readonly string _tempDir;

    public DefaultExcludesTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), "Unilyze_DefaultExcludesTests_" + Path.GetRandomFileName());
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try { Directory.Delete(_tempDir, recursive: true); }
        catch { /* best effort */ }
    }

    void WriteFile(string relativePath, string content)
    {
        var fullPath = Path.Combine(_tempDir, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        File.WriteAllText(fullPath, content);
    }

    void WriteAsmdef(string directory, string fileName, string json)
    {
        Directory.CreateDirectory(directory);
        File.WriteAllText(Path.Combine(directory, fileName), json);
    }

    [Fact]
    public void AnalyzeDirectory_ExcludesCsFilesUnderObj()
    {
        WriteFile("Valid.cs", "public class Valid { }");
        WriteFile("obj/Generated.cs", "public class GeneratedInObj { }");

        var excludes = DefaultExcludes.ResolveProjectPaths(_tempDir);
        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", excludeDirectories: excludes);

        Assert.Single(result.Types);
        Assert.Equal("Valid", result.Types[0].Name);
    }

    [Fact]
    public void AnalyzeDirectory_ExcludesAutoGeneratedHeader()
    {
        WriteFile("Valid.cs", "public class Valid { }");
        WriteFile("Generated.cs", """
            // <auto-generated>
            public class AutoGenerated { }
            """);

        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", excludeGeneratedCode: true);

        Assert.Single(result.Types);
        Assert.Equal("Valid", result.Types[0].Name);
    }

    [Fact]
    public void AnalyzeDirectory_ExcludesGcsSuffix()
    {
        WriteFile("Valid.cs", "public class Valid { }");
        WriteFile("Generated.g.cs", "public class GeneratedG { }");

        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", excludeGeneratedCode: true);

        Assert.Single(result.Types);
        Assert.Equal("Valid", result.Types[0].Name);
    }

    [Fact]
    public void AnalyzeDirectory_DisableGeneratedCodeExcludes_IncludesGeneratedFiles()
    {
        WriteFile("Generated.g.cs", "public class GeneratedG { }");

        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", excludeGeneratedCode: false);

        Assert.Single(result.Types);
        Assert.Equal("GeneratedG", result.Types[0].Name);
    }

    [Fact]
    public void NestedAsmdef_ParsesChildTypesOnlyOnce()
    {
        var parentDir = Path.Combine(_tempDir, "Parent");
        var childDir = Path.Combine(parentDir, "Child");

        WriteAsmdef(parentDir, "Parent.asmdef", """{"name": "Parent"}""");
        WriteAsmdef(childDir, "Child.asmdef", """{"name": "Child"}""");

        WriteFile("Parent/ParentType.cs", "public class ParentType { }");
        WriteFile("Parent/Child/ChildType.cs", "public class ChildType { }");

        var excludes = DefaultExcludes.ResolveProjectPaths(_tempDir);
        var asmdefs = AsmdefInfo.Discover(_tempDir, excludes);
        var parent = Assert.Single(asmdefs, a => a.Name == "Parent");
        var child = Assert.Single(asmdefs, a => a.Name == "Child");

        Assert.Contains(Path.GetFullPath(childDir), parent.ExcludeDirectories!);

        var parentResult = TypeAnalyzer.AnalyzeDirectoryWithTrees(
            parent.Directory, parent.Name, excludeDirectories: parent.ExcludeDirectories);
        var childResult = TypeAnalyzer.AnalyzeDirectoryWithTrees(
            child.Directory, child.Name, excludeDirectories: child.ExcludeDirectories);

        Assert.Single(parentResult.Types);
        Assert.Equal("ParentType", parentResult.Types[0].Name);

        Assert.Single(childResult.Types);
        Assert.Equal("ChildType", childResult.Types[0].Name);
        Assert.Equal("Child", childResult.Types[0].Assembly);

        var allNames = parentResult.Types.Concat(childResult.Types).Select(t => t.Name).ToList();
        Assert.Equal(allNames.Count, allNames.Distinct().Count());
    }

    [Fact]
    public void LoadMerged_AppliesDefaultExcludesWhenNotDisabled()
    {
        var excludes = UnilyzeConfig.BuildEffectiveExcludeDirs(UnilyzeConfig.Empty, _tempDir);

        Assert.NotNull(excludes);
        foreach (var name in DefaultExcludes.DirectoryNames)
            Assert.Contains(excludes!, e => e.EndsWith(Path.DirectorySeparatorChar + name, StringComparison.OrdinalIgnoreCase)
                || e.EndsWith(name, StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void LoadMerged_DisableDefaultExcludes_OmitsBuiltInDirs()
    {
        var config = new UnilyzeConfig(DisableDefaultExcludes: true);
        var excludes = UnilyzeConfig.BuildEffectiveExcludeDirs(config, _tempDir);

        Assert.Null(excludes);
    }

    [Fact]
    public void AnalyzeDirectory_ExcludesNestedObjUnderPackage()
    {
        WriteFile("Valid.cs", "public class Valid { }");
        WriteFile("Packages/Foo/ValidInPackage.cs", "public class ValidInPackage { }");
        WriteFile("Packages/Foo/obj/Gen.cs", "public class GeneratedInNestedObj { }");

        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", applyAnyDepthExcludes: true);

        Assert.Equal(2, result.Types.Count);
        Assert.DoesNotContain(result.Types, t => t.Name == "GeneratedInNestedObj");
    }

    [Fact]
    public void AnalyzeDirectory_DisableDefaultExcludes_IncludesNestedObj()
    {
        WriteFile("Packages/Foo/obj/Gen.cs", "public class GeneratedInNestedObj { }");

        var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(_tempDir, "Asm", applyAnyDepthExcludes: false);

        Assert.Single(result.Types);
        Assert.Equal("GeneratedInNestedObj", result.Types[0].Name);
    }

    [Fact]
    public void AnalyzeDirectory_AnyDepthExcludes_UsesRelativeSegmentsNotAbsolutePath()
    {
        var binParent = Path.Combine(Path.GetTempPath(), "Unilyze_binTrap_" + Path.GetRandomFileName(), "bin");
        var projectDir = Path.Combine(binParent, "myproject");
        Directory.CreateDirectory(projectDir);
        File.WriteAllText(Path.Combine(projectDir, "Valid.cs"), "public class Valid { }");

        try
        {
            var result = TypeAnalyzer.AnalyzeDirectoryWithTrees(projectDir, "Asm", applyAnyDepthExcludes: true);

            Assert.Single(result.Types);
            Assert.Equal("Valid", result.Types[0].Name);
        }
        finally
        {
            try { Directory.Delete(Path.GetDirectoryName(binParent)!, recursive: true); }
            catch { /* best effort */ }
        }
    }
}
